// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildStep } from "./BuildStep";

export type Bundle = { artifact: string, target: string, size_bytes: bigint, hash: string, drift: string, built_at: string, steps: Array<BuildStep>, };
