// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingLocation } from "./FindingLocation";

export type CheckFinding = { category: string, severity: string, rule: string, summary: string, detail: string | null, remediation: string | null, location: FindingLocation | null, };
