// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Run } from "./Run";

export type CrossProjectRun = { project_id: string, project_name: string, run: Run, };
