// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectMeta } from "./ProjectMeta";
import type { ProjectSummary } from "./ProjectSummary";

export type ProjectListItem = { meta: ProjectMeta, summary: ProjectSummary, };
