// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSummary = { runs: number, running: number, failed_24h: number, success_rate: number, tokens: bigint, last_activity: string | null, agents: number, engine_ok: boolean, };
