// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Provider = { name: string, installed: boolean, recommended: boolean, source: string, credentials_gated: boolean, };
