// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { ToolUser } from "./ToolUser";

export type ToolDetail = { name: string, version: string | null, source: string, provides: string, plugin_kind: string | null, binary: string | null, capabilities: Array<Capability>, used_by: Array<ToolUser>, };
