// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowEdge } from "./WorkflowEdge";
import type { WorkflowNode } from "./WorkflowNode";

export type WorkflowGraph = { workflow: string, nodes: Array<WorkflowNode>, edges: Array<WorkflowEdge>, };
